### ISSUE TITLE
New Set Feature Probs

### ISSUE THREAD

**Issue by kenglub** [sashaouellet/Helix#14]
**Describe the bug**
When creating a new "set," the new set does not show up in the set dropdown for assigning new props. 
Also, when clicking "Set Membership" on a right click of an asset, no options appear.

**To Reproduce**
1. File>New>Set
2. Named "Kitchen" and "CharacterProp"
3. Ctrl+E for new asset
4. In set dropdown, no new set appears.

1. Right-click on any asset in the Asset List
2. Select "Set Membership"
3. No options appear

**Expected behavior**
Expected to create a new set with a specified name and then have that new set appear in the set list dropdown for a new asset/prop.
Expected to right click on "Set Membership" and have options to change the set container.

**OS (please complete the following information):**
Windows 10

**Additional context**
cmd.exe reads: 
    File "I:\Savannah\CollaborativeSpace\helix\python\helix\manager\viewer.py", line 407 in handleSetMembership
        if s.id in el.setList:
AttributeError: 'Element' object has no attribute 'setList'

**Comment by sashaouellet** [comment]
Resolved, forgot to update elements and sequences tables with new sets column.
